# Base configs
baseurl:""

# UI configs
title: "Pankil Parikh"
name: "Pankil Parikh"
bio: "Computer Engineer"
social_urls:
  facebook: "https://www.facebook.com/pankil.parikh.900"
  instagram: "https://www.instagram.com/_pankilparikh22"
